# Header
menu:
  Home: /
  Archives: /archives
  Github:
    url: https://github.com/lmammino
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Loige.co

# URL of the Home page image
index_cover: /content/images/loige-co-header.jpg

# Default post title
default_post_title: New post

# Comments.
comments:
  # Disqus comments
  disqus_shortname: loige

# Google Analytics Tracking ID
google_analytics: UA-47248506-1

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/loige
twitter_handle: loige
github_url: https://github.com/lmammino
linkedin_url: https://www.linkedin.com/in/lucianomammino
mailto: lucianomammino@gmail.com
